### ISSUE TITLE
Doubt about Training

### ISSUE THREAD

**Issue by 980202006** [jthickstun/anticipation#6]
The effect of this model is amazing, I want to use my own data to train, but I am not proficient in jax. I encountered some bugs:
What is the version of levanter? I used the split_lakh branch, but I did not find the training entry, so I used the main branch, but encountered many problems.
What should be written in the tokenizer in the configuration file,
Should python src/levanter/main/train_lm.py --config_path be run to start training

**Comment by jthickstun** [comment]
The main branch of Levanter will definitely cause problems; among other things, as you have noticed it does not contain the utilities for tokenizing midi. The training script on the split-lakh branch is `levanter/examples/gpt2_example.py`. You can invoke this to train a small model with a command like:

python levanter/examples/gpt2_example.py --config_path levanter/config/lakh_small.yaml

**Comment by 980202006** [comment]
Thank you!I will try it.

**Comment by jthickstun** [comment]
Following up on this: training & finetuning anticipatory music transformers is now supported on Levanter main. See issue #7 for details. I'd recommend using main rather than the old split_lakh branch (unless you are trying to exactly replicate certain results from the paper) as (among other improvements) the documentation of Levanter has gotten more clear, preprocessing is streamlined, and GPU support is much improved.

**Comment by 980202006** [comment]
Thank You!
